import { GWS_MULTI_ACCOUNT_PLUGIN_PACKAGE } from '@/config'
import { CONTAINER_PORT } from '@/container/port'

import { GHCR_BASE_IMAGE_REPO } from './cli-version'
import { TYPECLAW_ENTRYPOINT_PATH } from './dockerfile'

export const MANAGED_RUNTIME_UID = 65532

export type BuildManagedRuntimeDockerfileOptions = {
  baseImageVersion: string
  baseImageRepository?: string
}

const RELEASE_VERSION = /^\d+\.\d+\.\d+$/
const IMAGE_REPOSITORY = /^[a-z0-9]+(?:[._-][a-z0-9]+)*(?::[0-9]+)?(?:\/[a-z0-9]+(?:[._-][a-z0-9]+)*)*$/

// Builds the version-paired immutable workload image. Release automation puts
// exact npm tarballs beside this Dockerfile, so the image never depends on the
// not-yet-published TypeClaw version being available from the registry.
export function buildManagedRuntimeDockerfile(options: BuildManagedRuntimeDockerfileOptions): string {
  if (!RELEASE_VERSION.test(options.baseImageVersion)) {
    throw new Error(`managed runtime base image must use a release version, got ${options.baseImageVersion}`)
  }
  const baseImageRepository = options.baseImageRepository ?? GHCR_BASE_IMAGE_REPO
  if (!IMAGE_REPOSITORY.test(baseImageRepository)) {
    throw new Error(`managed runtime base image repository is invalid: ${baseImageRepository}`)
  }

  return `# syntax=docker/dockerfile:1.7
# AUTOGENERATED by scripts/emit-managed-runtime-dockerfile.ts.
# Build context must contain exact typeclaw.tgz and
# typeclaw-gws-multi-account.tgz release inputs plus the source-controlled
# package.json/bun.lock production dependency graph.

FROM ${baseImageRepository}:${options.baseImageVersion}

WORKDIR /
COPY typeclaw.tgz /tmp/typeclaw.tgz
COPY typeclaw-gws-multi-account.tgz /tmp/typeclaw-gws-multi-account.tgz
COPY package.json bun.lock /tmp/runtime-install/

# Match the default host image tool surface and add tini as the PID 1 reaper
# required by bwrap's short-lived user namespaces.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    apt-get update \\
 && apt-get install -y --no-install-recommends ca-certificates curl gnupg \\
 && install -d -m 0755 /etc/apt/keyrings \\
 && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \\
      | gpg --dearmor --yes -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
 && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \\
      > /etc/apt/sources.list.d/github-cli.list \\
 && apt-get update \\
 && apt-get install -y --no-install-recommends gh tini tmux python3 python3-pip python3-venv python-is-python3 xvfb

# Install the complete production graph from the source-controlled lock, then
# extract the two exact direct packages without asking a registry resolver to
# mutate that graph. The default GWS package currently has no dependencies; the
# explicit assertion fails the build if that changes before the lock contract
# is updated deliberately.
RUN --mount=type=cache,target=/root/.bun/install/cache,sharing=locked \\
    cd /tmp/runtime-install \\
 && bun install --frozen-lockfile --production --ignore-scripts --linker=hoisted \\
 && cp -a node_modules/. /node_modules/ \\
 && mkdir -p /node_modules/typeclaw /node_modules/${GWS_MULTI_ACCOUNT_PLUGIN_PACKAGE} \\
 && tar -xzf /tmp/typeclaw.tgz --strip-components=1 -C /node_modules/typeclaw \\
 && tar -xzf /tmp/typeclaw-gws-multi-account.tgz --strip-components=1 -C /node_modules/${GWS_MULTI_ACCOUNT_PLUGIN_PACKAGE} \\
 && test -f /node_modules/typeclaw/src/cli/index.ts \\
 && test -f /node_modules/${GWS_MULTI_ACCOUNT_PLUGIN_PACKAGE}/package.json \\
 && test ! -e /node_modules/node_modules \\
 && cd /node_modules/typeclaw \\
 && bun -e 'await import("zod")' \\
 && bun -e 'const pkg = await Bun.file("/node_modules/${GWS_MULTI_ACCOUNT_PLUGIN_PACKAGE}/package.json").json(); if (Object.keys(pkg.dependencies ?? {}).length > 0) throw new Error("managed default plugin dependencies must be represented in the source-controlled runtime lock")' \\
 && rm -rf /tmp/runtime-install /tmp/typeclaw.tgz /tmp/typeclaw-gws-multi-account.tgz

# The runtime loads embeddings with remote access disabled. Bake the q8 model
# and compatibility sentinel before the root filesystem becomes immutable.
RUN TYPECLAW_HOME=/opt/typeclaw \\
    bun --smol run /node_modules/typeclaw/scripts/prepare-managed-runtime-models.ts

RUN groupadd --gid ${MANAGED_RUNTIME_UID} typeclaw \\
 && useradd --uid ${MANAGED_RUNTIME_UID} --gid ${MANAGED_RUNTIME_UID} --home-dir /home/typeclaw --no-create-home typeclaw \\
 && mkdir -p /agent /home/typeclaw \\
 && chown -R ${MANAGED_RUNTIME_UID}:${MANAGED_RUNTIME_UID} /agent /home/typeclaw

ENV NODE_ENV=production \\
    HOME=/home/typeclaw \\
    TYPECLAW_RUNTIME_HOME=/home/typeclaw \\
    TYPECLAW_ENTRYPOINT_RUNTIME=1 \\
    TYPECLAW_CLI_ENTRY=/node_modules/typeclaw/src/cli/index.ts \\
    TYPECLAW_DEPLOYMENT_PROFILE=managed \\
    TYPECLAW_MODEL_CACHE=/opt/typeclaw/models \\
    TYPECLAW_NETWORK_BLOCK_INTERNAL=0 \\
    GWS_CONFIG_HOME=/agent/workspace/.config/gws \\
    AGENT_MESSENGER_CONFIG_DIR=/agent/workspace/.config/agent-messenger

USER ${MANAGED_RUNTIME_UID}:${MANAGED_RUNTIME_UID}
WORKDIR /agent

HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \\
  CMD bun -e 'const response=await fetch("http://127.0.0.1:${CONTAINER_PORT}/health/live"); if (!response.ok) process.exit(1)'

ENTRYPOINT ["/usr/bin/tini", "--", "${TYPECLAW_ENTRYPOINT_PATH}"]
CMD ["run"]
`
}
